#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: rareshare-web-production
  config:
    BUNDLE_WITHOUT: "development:test"
    REDIS_PROVIDER: "REDISTOGO_URL"

staging:
  app: rareshare-web-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
